# Default token bucket settings
default.capacity=10
default.refillTokensPerSecond=5


# Per-API overrides
api.GET:/orders.capacity=20
#api.GET:/orders.refillTokensPerSecond=10


#api.POST:/orders.capacity=5
api.POST:/orders.refillTokensPerSecond=2