# Default token bucket settings
default.capacity=5
default.refillTokensPerSecond=1


# Per-API overrides
api.GET\:/orders.capacity=20
#api.GET\:/orders.refillTokensPerSecond=10

#api.POST\:/orders.capacity=5
api.POST\:/orders.refillTokensPerSecond=2